apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ghcr-login-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJtb25vcHRpYy1zdGFmZiIsInBhc3N3b3JkIjoiZ2hwXzVsMU9DOU5NUVduODY1TEhxa0VWdlFSQkVHT0hiejJmWG1JZSIsImVtYWlsIjoic3RhZmZAbW9ub3B0aWMuaW8iLCJhdXRoIjoiYlc5dWIzQjBhV010YzNSaFptWTZaMmh3WHpWc01VOURPVTVOVVZkdU9EWTFURWh4YTBWV2RsRlNRa1ZIVDBoaWVqSm1XRzFKWlE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
